// vue_test/src/components/Menu.vue
<template>
  <div>
    <div id="menu" class="menu-container" >

      <img alt="Logo" src="../assets/logo.png">
      <div class="framework" >
        <h1> Vue Test </h1>
      </div>

      <div class="buttons-container">
        <button class="Btn" @click="createRows(1000)"> Create 1000 rows </button>
        <button class="Btn" @click="addRows(1000)"> Add 1000 rows </button>
        <button class="Btn" @click="createRows(10000)"> Create 10 000 rows </button>
        <button class="Btn" @click="addRows(10000)"> Add 10 000 rows </button>
        <button class="Btn" @click="removeRows()"> Clear </button>
      </div>
    </div>
  </div>
</template>

<script>
  export default  {
    props: ['createRows', 'addRows', 'removeRows'],
  }
</script>

// angular-test/src/app/menu/menu.component.ts
import { Component, Output, EventEmitter} from '@angular/core';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})

export class MenuComponent {
  @Output() addEvent = new EventEmitter<number>();
  @Output() createEvent = new EventEmitter<number>();
  @Output() removeEvent = new EventEmitter<number>();

  addRows(val :number){
    this.addEvent.emit(val)
  }

  createRows(val :number){
    this.createEvent.emit(val)
  }

  removeRows(){
    this.removeEvent.emit(0)
  }
}

<div id="menu" class="menu-container" >

  <img alt="Logo" src="../assets/logo.png">
  <div class="framework" >
    <h1> Angular Test </h1>
  </div>

  <div class="buttons-container">
    <button class="Btn" (click)="createRows(1000)"> Create 1000 rows </button>
    <button class="Btn" (click)="addRows(1000)"> Add 1000 rows </button>
    <button class="Btn" (click)="createRows(10000)"> Create 10 000 rows </button>
    <button class="Btn" (click)="addRows(10000)"> Add 10 000 rows </button>
    <button class="Btn" (click)="removeRows()"> Clear </button>
  </div>
</div>
