// angular-test/src/app/rendering/rendering.component.ts
import { Component, Output, EventEmitter} from '@angular/core';
import buildData from '../../dummyData';

@Component({
  selector: 'app-rendering',
  templateUrl: './rendering.component.html',
  styleUrls: ['./rendering.component.css']
})

export class RenderingComponent {
  numberOfRows: number = 0;
  data: object[];
  add: number =  0;
  create: number =  0;
  @Output() addEvent = new EventEmitter<number>();
  @Output() createEvent = new EventEmitter<number>();
  @Output() removeEvent = new EventEmitter<number>();

  constructor() {
    console.log('RenderingComponent');
  }

  addRows(val :number){
    console.log('addRows', val)
    this.addEvent.emit(val)
  }

  createRows(val :number){
    this.createEvent.emit(val)
  }

  removeRows(){
    this.removeEvent.emit(0)
  }

  onAdd($event: number){
    this.numberOfRows = this.numberOfRows + $event;
    if (this.data === undefined) {
      this.data = buildData($event)
    } else {
      let data = this.data;
      this.data = data.concat(buildData($event))
    }
  }

  onCreate($event: number){
    this.numberOfRows = $event;
    this.data = buildData(this.numberOfRows)
  }

  onRemove(){
    this.numberOfRows = 0;
    this.data = [];
  }
}

<div id="rendering" class="rendering-container" >

  <img alt="Logo" src="../assets/logo.png">
  <div class="framework" >
    <h1> Angular Test </h1>
  </div>

  <div class="buttons-container">
    <button class="Btn" (click)="createRows(1000)"> Create 1000 rows </button>
    <button class="Btn" (click)="addRows(1000)"> Add 1000 rows </button>
    <button class="Btn" (click)="createRows(10000)"> Create 10 000 rows </button>
    <button class="Btn" (click)="addRows(10000)"> Add 10 000 rows </button>
    <button class="Btn" (click)="removeRows()"> Clear </button>
  </div>
</div>

<div id="app">
  <table class="data-table">
    <tbody>
      <app-row
        (addEvent)="onAdd($event)"
        (createEvent)="onCreate($event)"
        (removeEvent)="onRemove()"
        *ngFor="let row of data"
        [id]="row.id"
        [label]="row.label"
      ></app-row>
    </tbody>
  </table>
</div>

// vue_test/src/components/Rendering.vue
<template>
  <div>
    <div id="rendering" class="rendering-container">
      <img alt="Logo" src="../assets/logo.png">
      <div class="framework">
        <h1> Vue Test </h1>
      </div>
      <div class="buttons-container">
        <button class="Btn" @click="createRows(1000)"> Create 1000 rows </button>
        <button class="Btn" @click="addRows(1000)"> Add 1000 rows </button>
        <button class="Btn" @click="createRows(10000)"> Create 10 000 rows </button>
        <button class="Btn" @click="addRows(10000)"> Add 10 000 rows </button>
        <button class="Btn" @click="removeRows()"> Clear </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    createRows: Function,
    addRows: Function,
    removeRows: Function,
  },
}
</script>
