// react_test/src/components/Rendering.js
import React, { Component } from 'react';
import '../App.css';
import logo from '../logo.png'

class Rendering extends Component{
  render(){
    const { create, add,  remove } = this.props;
    return(
      <div className="menu-container" >

        <img src={logo} alt={'logo'} />
        <div className="framework" >
          <h1> React Test </h1>
        </div>

        <div className="buttons-container">
          <button id="create1000" className="Btn" onClick={() => create(1000) } >Create 1000 rows</button>
          <button id="add1000" className="Btn" onClick={() => {add(1000)}} >Add 1000 rows</button>
          <button id="create1000" className="Btn" onClick={() => {create(10000)}} >Create 10 000 rows</button>
          <button id="add10000" className="Btn" onClick={() => {add(10000)}} >Add 10 000 rows</button>
          <button id="delete" className="Btn" onClick={remove} >Clear</button>
        </div>
      </div>
    );
  }
}
export default Rendering;

// vue_test/src/components/Rendering.vue
<template>
  <div>
    <div id="rendering" class="rendering-container">
      <img alt="Logo" src="../assets/logo.png">
      <div class="framework">
        <h1> Vue Test </h1>
      </div>
      <div class="buttons-container">
        <button class="Btn" @click="createRows(1000)"> Create 1000 rows </button>
        <button class="Btn" @click="addRows(1000)"> Add 1000 rows </button>
        <button class="Btn" @click="createRows(10000)"> Create 10 000 rows </button>
        <button class="Btn" @click="addRows(10000)"> Add 10 000 rows </button>
        <button class="Btn" @click="removeRows()"> Clear </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    createRows: Function,
    addRows: Function,
    removeRows: Function,
  },
}
</script>
