// react_test/src/App.js
import React, { Component } from 'react';
import './App.css';
import Menu from './components/Menu';
import Row from './components/Row';
import buildData from './dummyData';

class App extends Component {

  state = {
    data:[],
  }

  create = (amount) => {
    this.setState({ data: buildData(amount) });
  }

  add = (amount) => {
    this.setState({ data: this.state.data.concat(buildData(amount)) });
  }

  remove = () => {
    this.setState({ data: [] });
  }


  render() {
    return (
      <div className="App">
        <Menu
          create={this.create}
          add={this.add}
          remove={this.remove}
        />

        <table className="data-table"><tbody>
          {this.state.data.map((item, i) => (
            <Row key={i} item={item} ></Row>
          ))}
        </tbody></table>

      </div>
    );
  }
}

export default App;

// angular-test/src/app/app.component.ts
import { Component } from '@angular/core';
import buildData from '../dummyData';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  numberOfRows: number = 0;
  data: object[];
  add: number =  0;
  create: number =  0;


  onAdd($event: number){
    this.numberOfRows = this.numberOfRows + $event;
    if (this.data === undefined) {
      this.data = buildData($event)
    } else {
      let data = this.data;
      this.data = data.concat(buildData($event))
    }
  }

  onCreate($event: number){
    this.numberOfRows = $event;
    this.data = buildData(this.numberOfRows)
  }

  onRemove(){
    this.numberOfRows = 0;
    this.data = [];
  }
}


<div id="app">
  <app-menu
    (addEvent)="onAdd($event)"
    (createEvent)="onCreate($event)"
    (removeEvent)="onRemove()"
  ></app-menu>

  <table class="data-table">
    <tbody>
      <app-row
        *ngFor="let row of data"
        [id]="row.id"
        [label]="row.label"
      ></app-row>
    </tbody>
  </table>
</div>
