// angular-test/src/app/row/row.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-row',
  templateUrl: './row.component.html',
  styleUrls: ['./row.component.css']
})

export class RowComponent {
  @Input() id: number;
  @Input() label: string;

}

<tr>
  <td class="small-col" > {{id}} </td>
  <td class="big-col" > {{label}} </td>
</tr>

// react_test/src/components/Row.js
import React, { Component } from 'react';

class Row extends Component {

  render() {
    let { item } = this.props;
    return (
      <tr className="data-row ">
        <td className="small-col" >{item.id}</td>
        <td className="big-col" >{item.label}</td>
      </tr>);
  }
}
export default Row;
